# Generated by Django 5.0.2 on 2024-02-09 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dragon',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID_дракона')),
                ('name', models.CharField(max_length=30, verbose_name='Назва дракона')),
                ('description', models.TextField(verbose_name='Опис')),
                ('availability', models.BooleanField(default=False, verbose_name='Чи є в заповіднику?')),
                ('photo', models.CharField(max_length=60, verbose_name='Посилання на фото')),
                ('bg_photo', models.CharField(max_length=45, verbose_name='Посилання на клас фото')),
            ],
        ),
    ]
