# Generated by Django 5.0.2 on 2024-02-10 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd_dragon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID_відвідувача')),
                ('first_name', models.CharField(max_length=20, verbose_name="Ім'я")),
                ('last_name', models.CharField(max_length=20, verbose_name='Прізвище')),
                ('email', models.EmailField(max_length=50, verbose_name='E-mail')),
            ],
            options={
                'verbose_name': 'Відвідувач',
                'verbose_name_plural': 'Відвідувачі',
            },
        ),
        migrations.AlterModelOptions(
            name='dragon',
            options={'verbose_name': 'Дракон', 'verbose_name_plural': 'Дракони'},
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Час')),
                ('dragon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bd_dragon.dragon')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bd_dragon.visitor')),
            ],
            options={
                'verbose_name': 'Візит',
                'verbose_name_plural': 'Візит',
            },
        ),
    ]
